import { Apple } from "./types";

export const apples: Apple[] = [
  {
    name: "Golden Delicious",
    image: "/golden-delicious.png",
    taste: "Douce et légèrement acidulée",
    utilization: "Polyvalente, idéale pour les tartes, compotes et salades",
    season: "Septembre à avril",
    color: "#F9DC5C",
    benefits: "Elle est pleine de vitamines pour te donner de la force.",
    subtitle: "La douceur dorée",
    nutrition: {
      calories: 52,
      carbohydrates: 14,
      fiber: 2.4,
      sugars: 12,
      vitaminC: 4.6,
    },
  },
  {
    name: "Granny Smith",
    image: "/granny-smith.png",
    taste: "Très acidulée, croquante",
    utilization:
      "Parfaite pour les desserts et à croquer, excellente en cuisine",
    season: "Octobre à avril",
    color: "#8DB600",
    benefits:
      "Croquante et pleine de vitamines, parfaite pour les super-héros en devenir.",
    subtitle: "L'acidulée verte",
    nutrition: {
      calories: 50,
      carbohydrates: 13.5,
      fiber: 3.0,
      sugars: 10,
      vitaminC: 5.0,
    },
  },
  {
    name: "Gala",
    image: "/gala.png",
    taste: "Douce et sucrée",
    utilization: "À croquer ou pour les jus de fruits",
    season: "Août à mars",
    color: "#FF6F61",
    benefits: "Protège tes dents et aide ton ventre à bien fonctionner.",
    subtitle: "La pomme joyeuse",
    nutrition: {
      calories: 53,
      carbohydrates: 14,
      fiber: 2.0,
      sugars: 12,
      vitaminC: 6.3,
    },
  },
  {
    name: "Fuji",
    image: "/fuji.png",
    taste: "Très sucrée et juteuse",
    utilization: "À croquer, pour les desserts ou les salades de fruits",
    season: "Octobre à mai",
    color: "#F7A072",
    benefits:
      "Elle est pleine d'énergie pour te donner la pêche toute la journée.",
    subtitle: "La douce trésor",
    nutrition: {
      calories: 63,
      carbohydrates: 16,
      fiber: 2.0,
      sugars: 13,
      vitaminC: 3.0,
    },
  },
  {
    name: "Pink Lady",
    image: "/pink-lady.png",
    taste: "Parfumée, sucrée et acidulée",
    utilization: "À croquer ou pour des recettes gourmandes",
    season: "Novembre à mai",
    color: "#F78FA7",
    benefits: "Bonne pour ton cœur et tes muscles grâce à ses antioxydants.",
    subtitle: "La princesse rose",
    nutrition: {
      calories: 60,
      carbohydrates: 15,
      fiber: 2.5,
      sugars: 13,
      vitaminC: 4.0,
    },
  },
  {
    name: "Reinette Grise du Canada",
    image: "/canada.png",
    taste: "Parfumée, acidulée et rustique",
    utilization: "Idéale pour les tartes et les compotes",
    season: "Octobre à mars",
    color: "#C2B280",
    benefits:
      "Riche en fibres, elle prend soin de ton ventre et favorise une bonne digestion.",
    subtitle: "La rustique parfaite",
    nutrition: {
      calories: 50,
      carbohydrates: 13,
      fiber: 3.0,
      sugars: 10,
      vitaminC: 6.0,
    },
  },
  {
    name: "Braeburn",
    image: "/baebrun.png",
    taste: "Équilibrée, sucrée et acidulée",
    utilization: "À croquer, en pâtisserie et en jus",
    season: "Octobre à avril",
    color: "#D2691E",
    benefits: "Excellente pour te donner de l'énergie et rester concentré.",
    subtitle: "L'aventurière gourmande",
    nutrition: {
      calories: 54,
      carbohydrates: 14,
      fiber: 2.2,
      sugars: 12,
      vitaminC: 4.0,
    },
  },
  {
    name: "Jonagold",
    image: "/jona.png",
    taste: "Douce et légèrement acidulée",
    utilization: "En cuisine, pour les desserts et les salades",
    season: "Octobre à avril",
    color: "#FDD365",
    benefits: "Renforce tes os et t'aide à grandir en pleine santé.",
    subtitle: "L'alliée savoureuse",
    nutrition: {
      calories: 55,
      carbohydrates: 14,
      fiber: 2.3,
      sugars: 12,
      vitaminC: 5.0,
    },
  },
  {
    name: "Honeycrisp",
    image: "/honey.png",
    taste: "Très sucrée, croquante et juteuse",
    utilization: "À croquer ou dans les salades",
    season: "Septembre à novembre",
    color: "#FFB07C",
    benefits: "Hydrate ton corps et te donne un super sourire !",
    subtitle: "La pomme bonheur",
    nutrition: {
      calories: 57,
      carbohydrates: 14.5,
      fiber: 2.0,
      sugars: 12.5,
      vitaminC: 3.5,
    },
  },
  {
    name: "Red Delicious",
    image: "/red-delicious.png",
    taste: "Sucrée et douce, peu acidulée",
    utilization: "Principalement à croquer",
    season: "Septembre à mai",
    color: "#A50021",
    benefits: "Riche en antioxydants pour te protéger comme une armure.",
    subtitle: "La rouge protectrice",
    nutrition: {
      calories: 50,
      carbohydrates: 12,
      fiber: 1.8,
      sugars: 10,
      vitaminC: 2.5,
    },
  },
];
