import type { Metadata } from "next";
import { Luckiest_Guy } from "next/font/google";
import "./globals.css";

// const fredoka = Fredoka({ subsets: ["latin"] });
const luckiestGuy = Luckiest_Guy({
  subsets: ["latin"],
  weight: "400", // Spécifiez le poids explicitement
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${luckiestGuy.className}`}>{children}</body>
    </html>
  );
}
